import wx


class ListSlider(wx.Panel):
    def __init__(self, parent, id=wx.ID_ANY, 
                 choices=None, # a list of strings
                 pos=wx.DefaultPosition, size=wx.DefaultSize, 
                 style=wx.SL_HORIZONTAL, # either SL_HORIZONTAL or SL_VERTICAL
                 name='ListSlider'):
        wx.Panel.__init__(self, parent, id, pos, size, name=name)
        self.slider = wx.Slider(self, maxValue=len(choices)-1, style=style)
        label_sizer: wx.GridSizer
        if style == wx.SL_HORIZONTAL:
            label_sizer = wx.GridSizer(1, len(choices), 0, 0)
            label_align = wx.ALIGN_CENTRE_HORIZONTAL
            root_sizer = wx.BoxSizer(wx.VERTICAL)
        else:
            label_sizer = wx.GridSizer(len(choices), 1, 0, 0)
            label_align = wx.ALIGN_CENTRE_VERTICAL
            root_sizer = wx.BoxSizer(wx.HORIZONTAL, border=1)
        for choice in choices:
            label_sizer.Add(wx.StaticText(self, wx.ID_ANY, choice), 0, label_align)
        root_sizer.Add(self.slider, 1, wx.EXPAND)
        root_sizer.Add(label_sizer, 0, wx.EXPAND)
        self.SetSizer(root_sizer)
        self.Fit()
        self.choices = choices
        self.slider.Bind(wx.EVT_SLIDER, self.on_slider)

    def on_slider(self, evt):
        # pretend the event was generated by "self", and let propagate
        evt.Skip()
        evt.SetEventObject(self)
        evt.SetId(self.GetId())
        evt.SetString(self.GetValue())

    def GetValue(self): # -> str !! 
        return self.choices[self.slider.GetValue()]

    def SetValue(self, value):
        self.slider.SetValue(self.choices.index(value))
